services:
  db:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    build: .
    command: >
      bash -c "celery -A core worker -l info & celery -A core beat -l info"
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_KEY: ${DJANGO_KEY}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DEBUG: ${DEBUG}
      HOST: ${HOST}
      REDIS_URL: "redis://redis:6379/1"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - redis
    restart: unless-stopped

networks:
  default:
    name: api
