# Generated by Django 5.2.1 on 2025-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('General Maintenance', 'general maintenance'), ('Electrical', 'electrical'), ('Plumbing', 'plumbing'), ('HVAC', 'hvac'), ('Landscaping', 'landscaping'), ('Pest Control', 'pest control'), ('Cleaning', 'cleaning'), ('Security', 'security'), ('Other', 'other')], max_length=19)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in progress'), ('Completed', 'completed'), ('On Hold', 'on hold'), ('Cancelled', 'cancelled')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
