name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:

env:
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  REGISTRY: ${{ vars.DIGITALOCEAN_REGISTRY_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:latest
